import { Finding, ScanResult, Category, Severity } from "./types.js";

const CATEGORY_LABELS: Record<Category, string> = {
  credential_exposure: "Credential Exposure",
  dangerous_skill_patterns: "Dangerous Skill Patterns",
  permission_configuration: "Permission & Configuration",
  hygiene: "Gitignore & Hygiene",
};

const CATEGORY_ORDER: Category[] = [
  "credential_exposure",
  "dangerous_skill_patterns",
  "permission_configuration",
  "hygiene",
];

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];

export function generateReport(result: ScanResult): string {
  const lines: string[] = [];

  lines.push("# ClawStack Sentinel Report");
  lines.push("");
  lines.push(`- **Timestamp:** ${result.timestamp}`);
  lines.push(`- **Scanned Path:** ${result.scanPath}`);
  lines.push(`- **Files Scanned:** ${result.filesScanned}`);
  lines.push(`- **Files Skipped:** ${result.filesSkipped}`);
  lines.push("");

  lines.push(`## Security Score: ${result.score} / 100 — ${result.bracket}`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Category | Critical | High | Medium | Low | Total |");
  lines.push("|----------|----------|------|--------|-----|-------|");

  for (const cat of CATEGORY_ORDER) {
    const catFindings = result.findings.filter((f) => f.category === cat);
    const counts: Record<Severity, number> = {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
    };
    for (const f of catFindings) {
      counts[f.severity]++;
    }
    const total = catFindings.length;
    lines.push(
      `| ${CATEGORY_LABELS[cat]} | ${counts.critical} | ${counts.high} | ${counts.medium} | ${counts.low} | ${total} |`
    );
  }
  lines.push("");

  // Detailed findings
  lines.push("## Detailed Findings");
  lines.push("");

  for (const cat of CATEGORY_ORDER) {
    const catFindings = result.findings.filter((f) => f.category === cat);
    if (catFindings.length === 0) continue;

    lines.push(`### ${CATEGORY_LABELS[cat]}`);
    lines.push("");
    lines.push("| Severity | File:Line | Finding | Recommended Fix |");
    lines.push("|----------|-----------|---------|-----------------|");

    // Sort by severity
    const sorted = [...catFindings].sort(
      (a, b) =>
        SEVERITY_ORDER.indexOf(a.severity) -
        SEVERITY_ORDER.indexOf(b.severity)
    );

    for (const f of sorted) {
      const location =
        f.lineNumber !== null ? `${f.filePath}:${f.lineNumber}` : f.filePath;
      const escapedContent = f.matchedContent
        .replace(/\|/g, "\\|")
        .replace(/\n/g, " ");
      const escapedFix = f.fix.replace(/\|/g, "\\|");
      lines.push(
        `| ${f.severity.toUpperCase()} | \`${location}\` | ${escapedContent} | ${escapedFix} |`
      );
    }
    lines.push("");
  }

  // Recommended next steps
  lines.push("## Recommended Next Steps");
  lines.push("");

  const sortedAll = [...result.findings].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) -
      SEVERITY_ORDER.indexOf(b.severity)
  );

  const topFindings = sortedAll.slice(0, 3);
  topFindings.forEach((f, i) => {
    const location =
      f.lineNumber !== null ? `${f.filePath}:${f.lineNumber}` : f.filePath;
    lines.push(
      `${i + 1}. **[${f.severity.toUpperCase()}]** ${f.patternName} in \`${location}\`: ${f.fix}`
    );
  });

  if (topFindings.length === 0) {
    lines.push("No issues found. Your deployment looks secure!");
  }

  lines.push("");
  lines.push("---");
  lines.push(
    "Generated by [ClawStack Sentinel](https://github.com/SkunkWorks0x/clawstack) — https://clawpilled.me"
  );
  lines.push("");

  return lines.join("\n");
}
